### ISSUE TITLE
version still shows "alpha"

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/shim#62]
Looks like we're missing a tag on the branch.

**Comment by amshinde** [comment]
There were no changes on the shim since the alpha, didnt seem right to cut a release on the shim with no changes at all.

**Comment by jodh-intel** [comment]
That makes sense, but it might look odd from a customer perspective if they see that the shim is alpha but other components are beta as overall the system is considered beta.

@sameo, @grahamwhaley - Thoughts on this? I had in fact added a new task to https://github.com/clearcontainers/runtime/wiki/Release-Checklist yesterday ("Update the versions of cc-proxy and cc-shim.") for the next release.

However, whatever approach we adopt (either re-tag to keep component versions "in sync", or leave as-is), I think we need to document it somewhere.

**Comment by grahamwhaley** [comment]
If we've found no issues with the shim in the alpha phase, then that is **a win** :-)
We should then move the shim to beta, even if there are no changes. The tag can point at the same commit, no problem.
If we then have to do a new, almost identical (the version string will be different...) package/release, then that is what we do. We need to make it clear the shim is not in alpha any more :-)

**Comment by jodh-intel** [comment]
@grahamwhaley - thanks. That aligns with my view so the changes I made to the checklist can remain (in fact I've updated them to be clearer still).

**Comment by gorozco1** [comment]
To be fixed in the next release

```
$ /usr/libexec/clear-containers/cc-shim --version
shim version: 3.0.0-alpha.4 (commit: 0)


$ rpm -qa | grep cc-shim
cc-shim-bin-3.0.0beta.2+git.1f545df-2.1.x86_64
cc-shim-3.0.0beta.2+git.1f545df-2.1.x86_64
```

**Comment by egernst** [comment]
alpha.4 was a lightweight tag and I updated it to be annotated as follows:
git push --delete origin 3.0.0-alpha.4
git tag -d 3.0.0-alpha.4
git tag -am "3.0.0-alpha.4 release" 3.0.0-alpha.4  ab14648
git push origin 3.0.0-alpha.4

You'll need to do a git fetch --tags to see this update. 

I added a tag as well for beta.1 @ ab14648

Can someone verify and close this please? @gorozco1 @jodh-intel @grahamwhaley

**Comment by jodh-intel** [comment]
We're still missing a tag for `3.0.0-alpha.3` but the rest look fine to me.

**Comment by egernst** [comment]
@jodh-intel added that tag as well.  Thanks James.
